### ISSUE TITLE
Scrolling UX Issues in demos

### ISSUE THREAD

**Issue by SideQuestDIY** [paper-leaf/alton#1]
This is pretty awesome. I did notice a few issues with your demos.
1. When you scroll all the way to the bottom or top the scroll delay before you can change directions makes you feel like the site has broken. Perhaps resetting the scroll delay when you hit the top of bottom will solve this. 
2. If you scroll using the scroll-bar to the bottom of the page, when you scroll up using the scroll wheel it scrolls as if it would without the script, then allows you to scroll down in the same manner. Perhaps its wise to use the scroll position with the scroll-bar to update the target as it goes, that way the same effect can be achieved with a mix of the two scrolling options.
3. Sometimes when you hit the top or bottom it does legitimately freezing until you refresh.

All-in-all I love what's going on here, im excited to try it out.

**Comment by ntan97** [comment]
Hey twittem,

Appreciate the time you're taking to take a peek and letting us know about any issues. 

Do you mind providing me your OS and Browser just so I can take a peek and see what's going on, and I'll jump on this and see what I can get going.

**Comment by SideQuestDIY** [comment]
Sure no problem.

Here are the specs the demo was tested with:
- Windows 8.1 Pro
- Google Chrome - Version 40.0.2214.115 m

**Comment by ntan97** [comment]
Perfect thanks so much. I'll address you're points in order here:
1. This is something that we had to implement in order to prevent double scrolls. We're aware that it's not perfect and needs some tweaking to get right. We've got an issue thread dedicated to this. 
2. This is another issue that has been pointed out, we'll be investigating the best way to tie these two together.
3. I'll have to investigate this one more thoroughly. I test regularly on a laptop with the same os and browser, and haven't noticed thus far so I'll try to grab a couple others and see what's going on. I'll try to keep you updated on any status we find on this.

**Comment by ntan97** [comment]
I'm moving all discussions of the excessive scroll delay issue to https://github.com/paper-leaf/alton/issues/5

**Comment by paper-leaf** [comment]
Hey Twittem, 

Just wanted to update you here, we've released Alton 1.1.0 which should be a lot more responsive during normal scrolling activity. This should take care of the excessive delay issues you were noticing.

We are working hard on the other bugs you have reported and will update as we have more information.

**Comment by ntan97** [comment]
Marking bug as resolved, and closing based on releases that were set to improve this and closing of major issue noted above.
