### ISSUE TITLE
Would it be possible to change height to min height?

### ISSUE THREAD

**Issue by con322** [paper-leaf/alton#11]
Hi I was wondering is it possible to change the style height to min-height as on mobile my content for each slide extends beyond the viewport height.

Or is there any other options/settings that can be used to change this happening or is this the wrong plugin for me?

**Comment by ntan97** [comment]
Hey Con322, 

Can you pass along the device, operating system, and browser that you are using, just to make sure I'm seeing the same thing as you are?

**Comment by con322** [comment]
I was just resizing the browser chrome on my desktop, does it work differently on mobile if so could you explain as I am currently working on localhost? 

Thanks. Awesome Plugin by the way.

**Comment by ntan97** [comment]
Hey Con322, 

With the scrolling blocks, they are meant to be the full height of the window, no more. Otherwise, when you scroll to the next content block, you would miss any content that overflows the slide. 

I hope that helps, and please let me know if you need further clarification on the above. We appreciate the kind words as well.
